### ISSUE TITLE
OUTSEG for pour point

### ISSUE THREAD

**Issue by Lauren-Somers** [awickert/GRASS-fluvial-profiler#2]
In Segment_tmp_4A_INFORMATION.txt file, the line that corresponds to the farthest downstream stream segment is missing the OUTSEG value where it should be 0 indicating the catchment pour point.

**Comment by awickert** [comment]
I had removed the lines that set the default value to 0 (i.e. if it does not flow to any stream on the map); I have re-added this to v.stream.network and v.gsflow.segments.
